---
- name: Installing OpenDataHub operator
  import_tasks: ./odh-operator.yaml
  become: false
  when: (ACTION == "create" or ACTION == "provision") and ocp4_workload_xray_pipeline_lab_install_odh_operator

- name: Install Minimal OpenDataHub
  import_tasks: ./odh.yaml
  become: false
  when: (ACTION == "create" or ACTION == "provision") and ocp4_workload_xray_pipeline_lab_install_odh

- name: "Create JupyterHub ConfigMap in ODH user project"
  k8s:
    state: present
    definition: "{{ lookup('template', 'odh/odh_base_nb_cm.yaml.j2') }}"
  vars:
    namespace: opendatahub
  when: (ACTION == "create" or ACTION == "provision") and ocp4_workload_xray_pipeline_lab_install_odh

- name: Installing KNative KafkaSource
  import_tasks: ./knative-kafkasource.yaml
  become: false
  when: (ACTION == "create" or ACTION == "provision") and ocp4_workload_xray_pipeline_lab_install_kafkasource

- name: Setting up workload for users
  debug:
    msg: "Setting up workload for {{ ocp4_workload_xray_pipeline_lab_user_count }} users"

- include_tasks: per_user_workload.yaml
  loop: "{{ range(1, 1 + (ocp4_workload_xray_pipeline_lab_user_count | int)) | list }}"
  loop_control:
    loop_var: t_user_num
  vars:
    t_user: "{{ocp4_workload_xray_pipeline_lab_user_base}}{{ t_user_num }}"
    t_user_project: "{{ocp4_workload_xray_pipeline_lab_user_base}}{{ t_user_num }}"

- include_tasks: demo_user_workload.yaml
  vars:
      t_user: "{{ocp4_workload_xray_pipeline_lab_user_base}}1"
      t_user_project: "{{ocp4_workload_xray_pipeline_lab_user_base}}1"

- name: Get RGW route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: openshift-storage
    name: s3-rgw
  register: rgw_url_external

- name: Get Web Console route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: openshift-console
    name: console
  register: r_console_route

- name: Set agnosticd_user_info 
  agnosticd_user_info:
    msg: >
      "OCP Web Console Route is: {{ web_console_url }}"
      "RGW External Route is: {{ rgw_url_external }}"
      "A demo project has fully been deployed for the user: {{ demo_project }}"
  vars:
    web_console_url: "https://{{ r_console_route.resources[0].spec.host }}"
    rgw_url_external: "https://{{ rgw_url_external[0].spec.host }}"
    demo_project: "{{ocp4_workload_xray_pipeline_lab_user_base}}1"

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
