---
# The role is needed for the aggregated role source-observer in knative-eventing
# to provide readonly access to "Sources".
# Ref: https://github.com/knative/eventing/tree/master/config/core/rolessource-observer-clusterrole.yaml.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventing-contrib-kafka-source-observer
  labels:
    eventing.knative.dev/release: devel
    duck.knative.dev/source: "true"
rules:
- apiGroups:
  - "sources.knative.dev"
  resources:
  - "kafkasources"
  verbs:
  - get
  - list
  - watch
