---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-kafka-controller-addressable-resolver
  labels:
    contrib.eventing.knative.dev/release: "v0.17.2"
subjects:
- kind: ServiceAccount# Necessary for conversion webhook. These are copied from the serving
  # TODO: Do we really need all these permissions?
  name: kafka-controller-manager
  namespace: knative-sources
# An aggregated ClusterRole for all Addressable CRDs.
# Ref: https://github.com/knative/eventing/tree/master/config/core/rolesaddressable-resolvers-clusterrole.yaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
