---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-source-webhook-certs
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: "v0.17.2"
# The data is populated at install time.
