---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
    contrib.eventing.knative.dev/release: "v0.17.2"
  name: kafka-source-webhook
  namespace: knative-sources
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    control-plane: kafka-controller-manager
