---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.kafka.sources.knative.dev
  labels:
    contrib.eventing.knative.dev/release: "v0.17.2"
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: kafka-source-webhook
      namespace: knative-sources
  failurePolicy: Fail
  name: validation.webhook.kafka.sources.knative.dev
