---
- name: Set state
  set_fact:
    state: present
  when: not ocp4_workload_rhtr_xraylab_workload_destroy|bool

- name: Set state
  set_fact:
    state: absent
  when: ocp4_workload_rhtr_xraylab_workload_destroy|bool

- name: Create Open Data Hub Operator Subscription
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'amq-streams-operator/subscription.yaml.j2' ) }}"

- name: Wait for the CRD to be available
  when: not ocp4_workload_rhtr_xraylab_workload_destroy|bool
  k8s_facts:
    api_version: "apiextensions.k8s.io/v1beta1"
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
    - kafkas.kafka.strimzi.io
  register: r_crds
  until: r_crds.resources|length > 0
  retries: 30
  delay: 10
